# Asimple makefile for the GCD program
Roots: Roots.class
chmod u+x Roots

Roots.class: Roots.java
javac -Xlint Roots.java

submit: Makefile Roots.java
 submit cmps012a-pt.w16 pa4 Makefile Roots.java

